### ISSUE TITLE
Github workflow for linting (flake8, black, isort) and testing

### ISSUE THREAD

**Issue by vegu** [fullctl/fullctl#3]
Github workflow for linting (`flake8`, `black`, `isort`) and testing, can look [here](https://github.com/20c/ctl/blob/master/.github/workflows/tests.yml) for an example.

Also fix `flake8` issues if there are any. Lets discuss things like "function too complex" prior to implementation changes though.

Failing unit tests can be ignored for the scope of this, we will tackle those separately.

**Comment by egfrank** [comment]
PR here: https://github.com/fullctl/fullctl/pull/4
